[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
optimizer = true
optimizer_runs = 1_000_000


[dependencies]
solady = "0.1.12"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
